# Generated by Django 3.0.6 on 2020-07-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('faq', 'FAQ')], max_length=20, null=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('side-image', 'Text with Side Image')], max_length=20, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images')),
                ('title', models.CharField(max_length=50, null=True)),
                ('subtitle', tinymce.models.HTMLField(blank=True, null=True)),
                ('button_1_link', models.URLField(blank=True, null=True)),
                ('button_1_text', models.CharField(blank=True, max_length=10, null=True)),
                ('button_2_link', models.URLField(blank=True, null=True)),
                ('button_2_text', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page', 'position', 'display'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
