from pathlib import Path

DATA_DIR = Path('data')
DATA_DIR.mkdir(exist_ok=True)

LOGS_DIR = Path('logs')
LOGS_DIR.mkdir(exist_ok=True)

SCREENSHOT_DIR = LOGS_DIR / 'screenshots'
SCREENSHOT_DIR.mkdir(exist_ok=True)

EXPERTISE = {
    'API',
    'AWS S3',
    'Automation',
    'Axios',
    'Backend development',
    'CSS',
    'CSS3',
    'Chat GPT',
    'ChatGPT',
    'Chatbot',
    'Classification',
    'Code reviewers',
    'Configuration',
    'Css animation',
    'DRF',
    'Data Science',
    'Data structure',
    'Debugging',
    'Design',
    'Development',
    'Django REST framework',
    'Django',
    'Dom',
    'Es6',
    'False',
    'Flask',
    'Full Stack',
    'Github',
    'HTML',
    'HTML/CSS',
    'HTML5',
    'Heroku',
    'Implementation',
    'Ipython notebook',
    'JSON',
    'JavaScript',
    'Javascript events',
    'Js',
    'Json api',
    'Mac os x',
    'Models',
    'Nuxt 3',
    'Nuxt',
    'Nuxt.js',
    'Nuxtjs',
    'Parsing',
    'Programming',
    'Pycharm',
    'Python 3.x',
    'Python pandas',
    'Python',
    'Python/django',
    'Python3',
    'RESTful Web Services',
    'Regex',
    'SQL',
    'SQLite',
    'Scripts',
    'Selenium',
    'Server side',
    'Software as a service',
    'Sqlalchemy',
    'Tailwind CSS',
    'Tailwind',
    'Tailwindcss',
    'Template',
    'Terminal',
    'Troubleshooting',
    'True',
    'Tutoring',
    'TypeScript',
    'Vanilla JS',
    'Vanilla JavaScript',
    'Vite',
    'Vite.js',
    'Vitejs',
    'Vue component',
    'Vue router',
    'Vue',
    'Vue.js',
    'Vuejs',
    'Vuex',
    'Web apis',
    'Web design',
    'Web development',
    'Web scraping',
    'Web',
    'Webdriver',
    'Website development',
    'automatic',
    'pandas',
}

EXPERTISE_SECOND_TIER = {
    'Nuxt 2',
    'cesium',
    'cesium js',
    'Python 2',
    'Python 2.7',
    'Node.js',
    'MySQL',
    'numpy',
}

USELESS_TAGS = {
    'automatic',
    'False',
    'True',
    'Automation',
}

EXPERTISE_BLACKLIST = {
    ' Aem',
    ' C ',
    ' C,',
    ' C.',
    ' Express ',
    ' GIS ',
    ' Lua ',
    ' Lua',
    ' R ',
    ' ai ',
    ' crypto ',
    ' sas ', 
    ' sas.'
    '3d graphics',
    '3d model',
    '3d numpy array',
    '3d numpy',
    '3d plotting',
    'AEM',
    'ANOVA',
    'AWS (Amazon Web Services)',
    'AWS Lambda',
    'AWS',
    'Ai (artificial intelligence)',
    'Airtable',
    'AlpineJS',
    'Amazon Web Services',
    'Android layout',
    'Android studio',
    'Angular',
    'Apache Spark',
    'Apache',
    'ArcGIS Sites',
    'ArcGIS',
    'Arcgis',
    'Artificial neural network',
    'Azure Cloud Services',
    'Azure data factory',
    'Azure devops',
    'Azure',
    'Bash',
    'Binary Tree',
    'Binarytree',
    'Bioinformatics',
    'Bitcoin',
    'Blender',
    'Blockchain',
    'Bootstrap 5',
    'Bootstrap',
    'Bot',
    'Bubble.io',
    'C#',
    'C++',
    'CUDA',
    'Celery',
    'Chrome extension',
    'Chromeextension',
    'Circleci',
    'Cloud architecture',
    'Cloud hosting',
    'Computer vision',
    'Cors',
    'Cryptocurrency',
    'Cypress',
    'Cyrptocurrency',
    'Data analysis',
    'Data analytics',
    'Data engineering',
    'Data mining',
    'Data visualization',
    'Dax',
    'Deep Learning',
    'Docker',
    'Dreamweaver',
    'ELT pipeline',
    'ETL',
    'Electron',
    'Embedded Systems',
    'Express (express.js)',
    'Express Js',
    'Facebook ads',
    'Facebook ads',
    'Facebook pixel',
    'Facebook',
    'Fibonacci sequence',
    'Fibonacci series',
    'Fibonacci',
    'Firebase authentication'
    'Firebase authentication',
    'Firebase database',
    'Firebase database',
    'Firebase storage',
    'Firebase',
    'Firestore',
    'Fragment',
    'Functional testing',
    'GCP',
    'GCSE',
    'Go (Golang)',
    'Google Analytics',
    'Google Apps Script',
    'Google Cloud Platform',
    'Google Data Studio',
    'GraphQL',
    'Greensock',
    'Grid tiling',
    'Gunicorn',
    'Handlebars',
    'Handlebars.js',
    'Html canvas',
    'Html5 canvas',
    'IG accounts',
    'IIS',
    'Image processing',
    'Inkscape',
    'Instagram',
    'Internationalisation',
    'Internationalization',
    'Interview preparation',
    'Interview',
    'JAX-Based',
    'JAX/Haiku',
    'JUnit',
    'Java EE',
    'Jest',
    'Kafka',
    'Vbscript',
    'Kdb',
    'Kivy',
    'Kotlin',
    'Laravel 5',
    'Laravel',
    'Latexdiff',
    'Leetcode',
    'Linked List',
    'Linkedlist',
    'Linux',
    'MATLAB',
    'MERN Stack',
    'MVC',
    'Machine Learning',
    'Mail',
    'Mailchimp',
    'Material ui',
    'Materialize css',
    'Matplotlib',
    'Meta business suite',
    'Mocking',
    'MongoDB',
    'Mongodb + mongoose',
    'Mpi',
    'Mql5',
    'NGINX',
    'NLP (Natural Language Processing)',
    'Natural Language',
    'Network security',
    'Neural network',
    'Neural networks',
    'Next.js',
    'Nextjs',
    'Node.js',
    'Nodejs',
    'OpenCV',
    'P5.js',
    'PCA',
    'PHP',
    'Parallel programming',
    'Pinescript',
    'Polymer',
    'Power BI',
    'Protractor',
    'PyTorch',
    'Pygame',
    'Pyqt',
    'Pytest',
    'Python anywhere',
    'R Shiny',
    'RDF',
    'RHEL 8',
    'RML',
    'Raspberry Pi',
    'React Native',
    'React with redux',
    'React',
    'Reactjs',
    'Recursive Divide',
    'Redis',
    'Reinforcement learning ',
    'Reinforcement learning',
    'Rstudio',
    'Ruby on Rails',
    'Rubygem',
    'Scikit learn (sklearn)',
    'Scipy',
    'Search engine optimization',
    'Serverless',
    'Servicenow',
    'Shopify',
    'Simulink',
    'Socket.IO',
    'Solidity',
    'Sparql',
    'Speech Recognition',
    'Speech Synthesis',
    'Squarespace',
    'Stata',
    'Statistics',
    'Stripe',
    'Svelte',
    'Swift',
    'Symfony',
    'Technical writing',
    'Tensorflow',
    'Test Automation',
    'Three.js',
    'Trading',
    'Tradingview',
    'Ubuntu',
    'Unit testing',
    'Video streaming',
    'Vuetify',
    'Webflow',
    'Webrtc',
    'Windows Server',
    'Wix',
    'WooCommerce',
    'Word Press',
    'Wordpress',
    'YARRRML',
    'Zapier',
    'apps script',
    'appsscript',
    'aurora database',
    'crypto ',
    'crypto-js',
    'data mining',
    'dxf',
    'dynamodb',
    'game',
    'gurobi',
    'hacker',
    'internet of things',
    'jQuery',
    'jenkins',
    'kernal',
    'linear regression',
    'metamask',
    'micropython',
    'non-linear programming',
    'p5',
    'p5.js',
    'p5js',
    'pipeline',
    'pythonanywhere',
    ' ROS ',
    'prediction',
    'qualitiative predictors',
    'spark',
    'storyblok',
    'streamlit',
    'test case',
    'testcase',
    'testcase',
    'tower of hanoi',
    'trading strategies',
    'trading strategy',
    'unit test',
    'unittest',
    'webhook',
    'webpack',
    'Geospatial',
    'Google App Engine',
}


# Safety check
lowercase_expertise_blacklist = [expertise.lower() for expertise in EXPERTISE_BLACKLIST]
for expertise in EXPERTISE:
    if expertise.casefold() in lowercase_expertise_blacklist:
        raise Exception(f'Expertise in blacklist: {expertise}')


CAN_HELP_MESSAGE_TEMPLATE = '''\
Hey {client_name}!

I'd love to help you with this 🙂.

Would you like to schedule a call?\
'''