# Generated by Django 4.2.5 on 2023-09-28 17:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pricing_model', models.CharField(choices=[('Hourly', 'Hourly'), ('Monthly', 'Monthly'), ('Project', 'Project')], default='Hourly', max_length=255)),
                ('cta', models.CharField(default='Order Now', max_length=255, verbose_name='Call to Action')),
                ('cta_url', models.URLField(blank=True)),
                ('pre_cta', models.CharField(default='Learn More', help_text='The Call to action BEFORE ', max_length=255, verbose_name='Call to Action (Before Page)')),
                ('redirect_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceCollection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name_plural': 'Service Collections',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=50)),
                ('author_last_name', models.CharField(max_length=50)),
                ('author_bio', models.CharField(max_length=255)),
                ('author_profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/author-images/')),
                ('star_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('live', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
