# Generated by Django 3.0 on 2020-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menucategory_menuitem_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('body', models.TextField(null=True)),
                ('buttton_link', models.URLField(blank=True, null=True)),
                ('button_text', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
