# Generated by Django 3.0 on 2020-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200421_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploresection',
            old_name='buttton_link',
            new_name='button_link',
        ),
        migrations.AddField(
            model_name='exploresection',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exploresection',
            name='button_text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
