# Generated by Django 3.0 on 2020-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200421_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
