# Generated by Django 3.0 on 2020-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200421_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
