# Generated by Django 3.0 on 2020-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200421_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploresection',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(help_text='Image must be formatted to a 1:1 ratio (square image).', upload_to='images'),
        ),
    ]
