# Generated by Django 3.0 on 2020-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200421_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploresection',
            name='image_position',
            field=models.CharField(choices=[('auto', 'Auto'), ('left', 'Left'), ('right', 'Right')], default='auto', max_length=5),
        ),
        migrations.AddField(
            model_name='exploresection',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
