# Generated by Django 3.0.5 on 2020-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200421_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exploresection',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='exploresection',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
