# Generated by Django 3.0.5 on 2020-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200424_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'display', 'name']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
