# Generated by Django 3.0.5 on 2020-08-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'display', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['title'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
