# Generated by Django 3.0.5 on 2020-08-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200804_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'display', 'name'], 'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['title'], 'verbose_name': 'Menu item'},
        ),
    ]
