"""easymigrate

Revision ID: 19960c073fec
Revises: 265bd6c7ddec
Create Date: 2023-08-31 00:21:53.158074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19960c073fec'
down_revision: Union[str, None] = '265bd6c7ddec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_job')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_budget', sa.Integer(), nullable=True))
        batch_op.drop_column('expected_budget_amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_budget_amount', sa.INTEGER(), nullable=False))
        batch_op.drop_column('expected_budget')

    op.create_table('_alembic_tmp_job',
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tags', sa.TEXT(), nullable=False),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expected_budget_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('is_fully_updated', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('can_help', sa.BOOLEAN(), nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), nullable=True),
    sa.Column('is_applied_to', sa.BOOLEAN(), nullable=True),
    sa.Column('expected_budget', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###
