"""easymigrate

Revision ID: 265bd6c7ddec
Revises: 93e8daa00441
Create Date: 2023-08-30 22:17:46.523368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265bd6c7ddec'
down_revision: Union[str, None] = '93e8daa00441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True, comment='Whether the job is still open or not.'))
        batch_op.add_column(sa.Column('is_applied_to', sa.Boolean(), nullable=True, comment='Whether or not the job has already been applied to.'))
        batch_op.drop_column('is_applied')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_applied', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_applied_to')
        batch_op.drop_column('is_open')

    # ### end Alembic commands ###
