"""Add is_ignored column

Revision ID: 4928cf8d42b3
Revises: ce7e33d6fa1f
Create Date: 2023-09-01 00:12:43.420595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4928cf8d42b3'
down_revision: Union[str, None] = 'ce7e33d6fa1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ignored', sa.Boolean(), nullable=True, comment='Whether or not the job should be ignored by the bot.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('is_ignored')

    # ### end Alembic commands ###
