"""easymigrate

Revision ID: 93e8daa00441
Revises: 1527035a5c3c
Create Date: 2023-08-30 21:13:39.374102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e8daa00441'
down_revision: Union[str, None] = '1527035a5c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_help', sa.Boolean(), nullable=True, comment='Whether or not the job can be helped by a mentor.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('can_help')

    # ### end Alembic commands ###
