# Generated by Django 3.0.6 on 2020-07-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Account Name')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Account Description')),
                ('live', models.BooleanField(default=False, verbose_name='Live')),
                ('profile_pic_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='Profile Picture URL')),
                ('monitor', models.BooleanField(default=True)),
                ('followers', models.IntegerField(blank=True, null=True, verbose_name='Account Followers')),
                ('followers_data', models.TextField(blank=True, null=True, verbose_name='Followers over time')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What does this streamer call himself / herself?', max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streams.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_id', models.CharField(max_length=200, null=True, unique=True, verbose_name='Broadcast-ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('live', models.BooleanField(default=False, verbose_name='Live')),
                ('start_time', models.DateTimeField(help_text='Use yyyy-mm-dd hh:mm:ss format with hyphens.', null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('viewer_data', models.TextField(blank=True, null=True, verbose_name='Viewer Data')),
                ('likes_data', models.TextField(blank=True, null=True, verbose_name='Likes Data')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
                ('peak_viewers', models.PositiveIntegerField(default=0, verbose_name='Peak Viewers')),
                ('average_viewers', models.PositiveIntegerField(default=0, verbose_name='Average Viewers')),
                ('current_viewers', models.PositiveIntegerField(default=0, verbose_name='Current Viewers')),
                ('cumulative_viewers', models.PositiveIntegerField(default=0, verbose_name='Cumulative Viewers')),
                ('cover_frame_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='Cover Frame')),
                ('cobroadcasters', models.TextField(blank=True, null=True, verbose_name='Co-Broadcaster')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streams.Account', verbose_name='Host')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streams.Platform', verbose_name='Platform')),
            ],
            options={
                'ordering': ['start_time', 'host'],
            },
        ),
        migrations.CreateModel(
            name='APIAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('client_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Client ID')),
                ('auth_token', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Authentication/bearer Token')),
                ('api_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='API Key')),
                ('blacklist', models.BooleanField(default=False, verbose_name='Blacklist Flag')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streams.Platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'API Account',
                'verbose_name_plural': 'API Accounts',
                'ordering': ['platform', 'email'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streams.Platform'),
        ),
        migrations.AddField(
            model_name='account',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Streamer'),
        ),
    ]
