# Generated by Django 3.0.6 on 2020-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccount',
            name='auth_token',
            field=models.CharField(blank=True, max_length=5120, null=True, verbose_name='Authentication/bearer Token'),
        ),
    ]
