# Generated by Django 3.0.6 on 2020-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20200717_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
    ]
