# Generated by Django 3.0.5 on 2020-07-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_merge_20200718_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='score',
        ),
    ]
