# Generated by Django 3.0.5 on 2020-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_remove_stream_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
    ]
