# Generated by Django 3.0.5 on 2020-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_stream_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
