# Generated by Django 3.0.5 on 2020-07-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_account_profile_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_link',
            new_name='link',
        ),
    ]
