# Generated by Django 3.0.5 on 2020-07-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_auto_20200718_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='broadcast_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Broadcast-ID'),
        ),
    ]
