# Generated by Django 3.0.5 on 2020-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_auto_20200718_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='automatic',
            field=models.BooleanField(default=True),
        ),
    ]
