# Generated by Django 3.0.5 on 2020-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_stream_automatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='automatic',
        ),
    ]
