# Generated by Django 3.0.5 on 2020-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_remove_stream_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='automatic',
            field=models.BooleanField(default=True),
        ),
    ]
