# Generated by Django 3.0.5 on 2020-07-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_stream_automatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='automatic',
        ),
        migrations.AddField(
            model_name='stream',
            name='shady',
            field=models.BooleanField(default=False),
        ),
    ]
