# Generated by Django 3.0.5 on 2020-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_auto_20200723_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='average_viewers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Average Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cumulative_viewers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cumulative Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='current_viewers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='peak_viewers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peak Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
