# Generated by Django 3.0.5 on 2020-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0014_auto_20200725_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='average_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Average Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cumulative_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Cumulative Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='current_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='peak_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Peak Viewers'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
    ]
