# Generated by Django 4.2.6 on 2023-10-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exemplars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exemplars.category'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='character',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
